
spring:
  profiles:
    active: local
  batch:

---
spring:
  profiles: local
  datasource:
    url: jdbc:sybase:Tds:129.100.254.242:4000/tip?CHARSET=eucksc
    username: tip
    password: tipuse
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver